services:
  postgres_mvp_sprint_3:
    image: postgres:15
    container_name: postgres_mvp_sprint_3
    environment:
      POSTGRES_USER: mvp_user
      POSTGRES_PASSWORD: mvp_pass
      POSTGRES_DB: users_db
    ports:
      - "5454:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mvpnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_mvp
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mvpnet

  users_api:
    build: .
    container_name: users_api
    depends_on:
      - postgres_mvp_sprint_3
      - rabbitmq
    environment:
      DATABASE_URL: postgresql://mvp_user:mvp_pass@postgres_mvp_sprint_3:5432/users_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq_mvp:5672/
    ports:
      - "8000:8000"
    networks:
      - mvpnet

volumes:
  pgdata:

networks:
  mvpnet:
