version: '3.8'
services:
  users-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: usersdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata_users:/var/lib/postgresql/data
    networks:
      - mvpnet


  users-api:
    build: .
    env_file: .env
    depends_on:
      - users-postgres
    ports:
      - "8001:8001"
    networks:
      - mvpnet


volumes:
  pgdata_users:

networks:
  mvpnet:
    external: true
